import { NextPage } from 'next'
import Link from 'next/link'
import { motion } from 'framer-motion'
import langs from '../utils/langs'
import { useDispatch, useSelector } from 'react-redux'
import { RootState } from '../redux/store'
import { AiOutlineArrowLeft, AiOutlineArrowRight } from 'react-icons/ai'
import Head from 'next/head'
import { toggleTransition } from '../redux/navSlice'
import AboutSection from '../components/AboutSection'

const About: NextPage = () => {
  const { lang } = useSelector((state: RootState) => state.nav)
  const dispatch = useDispatch()

  return (
    <main className="overflow-hidden dark:text-white">
      <Head>
        <title>{'Peter Bartko | ' + langs[lang]['about']}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <motion.div
        initial={{ y: -300, x: -300, opacity: 0 }}
        animate={{ y: 0, x: 0, opacity: 1 }}
        exit={{ y: 300, x: 300, opacity: 0 }}
        className="min-h-screen grid place-content-center p-5"
      >
        <Link href="/">
          <a className="flex items-center w-fit space-x-1 top-3 left-3 fixed">
            <AiOutlineArrowLeft size={18} /> <p>{langs[lang]['back']}</p>
          </a>
        </Link>

        <AboutSection />

        <Link href="/projects">
          <a
            href="#"
            onClick={() => dispatch(toggleTransition(false))}
            className="text-pink-400 flex items-center gap-1 mt-5"
          >
            <p className="text-lg">{langs[lang]['my_projects']}</p>
            <AiOutlineArrowRight size={25} />
          </a>
        </Link>
      </motion.div>
    </main>
  )
}

export default About
