import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { AnimatePresence, motion } from 'framer-motion'
import langs from '../utils/langs'
import { Spin as Hamburger } from 'hamburger-react'
import { RootState } from '../redux/store'
import { useDispatch, useSelector } from 'react-redux'
import { toggleTransition } from '../redux/navSlice'
import { useState } from 'react'
import dynamic from 'next/dynamic'

const Home: NextPage = () => {
  const [menu, setMenu] = useState(false)
  const { lang } = useSelector((state: RootState) => state.nav)
  const dispatch = useDispatch()

  const Mobile = dynamic(() => import('../components/Mobile'), {
    ssr: false,
  })

  return (
    <main className="overflow-hidden dark:text-white">
      <Head>
        <title>Peter Bartko</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ y: 0, x: 0, opacity: 1 }}
        className="relative min-h-screen overflow-hidden grid place-content-center"
      >
        <motion.h1
          initial={{ scale: 0.5 }}
          animate={{ scale: 1 }}
          className="w-[320px] sm:w-full max-w-3xl font-normal text-2xl sm:text-4xl drop-shadow-md select-none"
        >
          {langs[lang]['h11']}
          <u className="bg-clip-text px-3 text-transparent bg-gradient-to-r animate-hue from-blue-400 to-cyan-500">
            Peter Bartko
            <br />
          </u>
          {langs[lang]['h12']} 👨‍💻
          <u className="text-xl sm:text-3xl no-underline text-zinc-700 dark:text-zinc-500">
            <br />
            {langs[lang]['h13']}
          </u>
        </motion.h1>

        <Link href="/about">
          <motion.a
            initial={{ y: -100, x: -100 }}
            animate={{ y: 0, x: 0 }}
            className="hidden uppercase sm:block fixed p-3 top-0 left-0 transition-colors hover:text-sky-400 cursor-pointer"
          >
            {langs[lang]['about']}
          </motion.a>
        </Link>

        <Link href="/projects">
          <motion.a
            onClick={() => dispatch(toggleTransition(true))}
            initial={{ y: 100, x: -100 }}
            animate={{ y: 0, x: 0 }}
            className="hidden uppercase sm:block fixed p-3 bottom-0 left-0 transition-colors hover:text-sky-400 cursor-pointer"
          >
            {langs[lang]['projects']}
          </motion.a>
        </Link>

        <Link href="/contact">
          <motion.a
            onClick={() => dispatch(toggleTransition(true))}
            initial={{ y: 100, x: 100 }}
            animate={{ y: 0, x: 0 }}
            className="hidden sm:block uppercase fixed p-3 bottom-0 right-0 transition-colors hover:text-sky-400 cursor-pointer"
          >
            {langs[lang]['contact']}
          </motion.a>
        </Link>

        <div className="block sm:hidden fixed top-0 left-1 z-[60]">
          <Hamburger size={22} onToggle={setMenu} toggled={menu} />
        </div>
        <AnimatePresence>
          {menu && (
            <motion.div
              key="menu"
              exit={{ opacity: 0 }}
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              onClick={() => setMenu(false)}
              className="fixed inset-0 bg-black/40 backdrop-blur-md z-50 flex flex-col gap-4 items-center justify-center"
            >
              <a href="#about" className="text-2xl">
                {langs[lang]['about']}
              </a>
              <a href="#projects" className="text-2xl">
                {langs[lang]['projects']}
              </a>
              <a href="#contact" className="text-2xl">
                {langs[lang]['contact']}
              </a>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>

      <Mobile />
    </main>
  )
}

export default Home
