import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { FaGithub } from 'react-icons/fa'
import { BsMoon, BsSun } from 'react-icons/bs'
import { useEffect, useState } from 'react'
import { CircleFlag } from 'react-circle-flags'
import { motion } from 'framer-motion'
import ParticlesBG from '../components/ParticlesBG'
import langs from '../utils/langs'
import { Spin as Hamburger } from 'hamburger-react'

const Home: NextPage = () => {
  const [dark, setDark] = useState(false)
  const [lang, setLang] = useState('en')

  useEffect(() => setDark(localStorage.theme === 'light'), [])

  useEffect(() => {
    if (
      localStorage.theme === 'dark' ||
      (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)
    ) {
      document.documentElement.classList.add('dark')
    } else {
      document.documentElement.classList.remove('dark')
    }
  }, [dark])

  const handleDarkMode = () => {
    setDark(m => {
      if (m) localStorage.theme = 'dark'
      else localStorage.theme = 'light'
      return !m
    })
  }

  const handleLanguage = () => {
    setLang(l => {
      if (l === 'sk') return 'en'
      else return 'sk'
    })
  }

  return (
    <main className="overflow-hidden dark:text-white">
      <Head>
        <title>Peter Bartko</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed inset-0 -z-10 dark:bg-black"></div>
      <ParticlesBG dark={dark} />

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ y: 0, x: 0, opacity: 1 }}
        className="relative min-h-screen overflow-hidden grid place-content-center"
      >
        <motion.h1
          initial={{ scale: 0.5 }}
          animate={{ scale: 1 }}
          className="w-[320px] sm:w-full max-w-3xl font-normal text-2xl sm:text-4xl drop-shadow-md select-none"
        >
          {langs[lang]['h11']}
          <u className="bg-clip-text px-3 text-transparent bg-gradient-to-r animate-hue from-blue-400 to-cyan-500">
            Peter Bartko
            <br />
          </u>
          {langs[lang]['h12']} 💻
          <u className="text-xl sm:text-3xl no-underline text-zinc-700 dark:text-zinc-500">
            <br />
            {langs[lang]['h13']}
          </u>
        </motion.h1>
        <Link href="/about">
          <motion.a
            initial={{ y: -100, x: -100 }}
            animate={{ y: 0, x: 0 }}
            href="/about"
            className="hidden sm:block fixed p-3 top-0 left-0"
          >
            {langs[lang]['about']}
          </motion.a>
        </Link>
        <div className="fixed top-0 left-1">
          <Hamburger size={22} />
        </div>
        <Link href="/projects">
          <motion.a
            initial={{ y: 100, x: -100 }}
            animate={{ y: 0, x: 0 }}
            className="hidden sm:block fixed p-3 bottom-0 left-0"
            href="#"
          >
            {langs[lang]['projects']}
          </motion.a>
        </Link>
        <div className="fixed p-3 top-0 right-0 flex items-center space-x-2">
          <button onClick={handleDarkMode}>
            {dark ? (
              <BsMoon size={20} className="hover:text-blue-800 transition-colors" />
            ) : (
              <BsSun size={20} className="hover:text-yellow-300 transition-colors" />
            )}
          </button>
          <button onClick={handleLanguage}>
            {lang === 'sk' ? (
              <CircleFlag countryCode="gb" height={20} width={20} />
            ) : (
              <CircleFlag countryCode="sk" height={20} width={20} />
            )}
          </button>
          <a href="https://github.com/PeterBartko" rel="noreferrer" target="_blank">
            <FaGithub size={20} className="hover:text-blue-500 transition-colors" />
          </a>
        </div>
        <motion.a
          initial={{ y: 100, x: 100 }}
          animate={{ y: 0, x: 0 }}
          className="hidden sm:block fixed p-3 bottom-0 right-0"
          href="#"
        >
          {langs[lang]['contact']}
        </motion.a>
      </motion.div>
    </main>
  )
}

export default Home
